name: Security check - Bandit

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Security check - Bandit
      uses: ioggstream/bandit-report-artifacts@v0.0.2
      with:
        project_path: .
        ignore_failure: true
    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Security report
        path: output/security_report.txt